### ISSUE TITLE
Serialization of attribute "properties"

### ISSUE THREAD

**Issue by nikolauskrismer** [opendatalab-de/geojson-jackson#14]
The GeoJson that is produced by geojson-jackson in combination with my mapper (a plain old MAPPER without any special configuration) does not seem to be valid geojson (according to geojsonlint.com and the GeoJSON specification).

The reason is that the properties field is not added to Features if there are no properties. According to the specification this is not valid. From http://geojson.org/geojson-spec.html: "The value of the properties member is an object (any JSON object or a JSON null value)."

It is valid to pass an empty object or a null value. To get the created string value validated, I had to add a mixin to my mapper that includes the following code:
```java
abstract class FeatureMixIn {
	@JsonInclude(Include.ALWAYS)
	public abstract Map<String, Object> getProperties();
}
```
However, this adds an empty object and not a null value. In fact I'd expect "null" and not an empty object, but since this behavior is valid GeoJSON that's OK for me.

Shouldn't the @JsonInclude(Include.NON_EMPTY) in the GeoJsonObject class be changed to ALWAYS for the Feature subclass (any maybe for other subclasses as well... I did not check this)??

Maybe this should also be done for the geometry type as well, since the GeoJSON specification also states that this field has to exist for valid GeoJSON.

**Comment by grundid** [comment]
thank you for noting that.

**Comment by nikolauskrismer** [comment]
Hmm... I am not sure if the implementation in the version 1.4 is correct.
The feature now contains the geometry and properties object... so this is OK and the bug has been fixed.

BUT:
Now also a featuteCollection and other objects (such as MultiLineStrings) also contain these members. Why did you implemented this? It does not violate the spec, but I guess this is not the intention of it :-)

**Comment by grundid** [comment]
Yes, your are right. I'm sorry for that. I'll fix this error ASAP.

**Comment by grundid** [comment]
Hi @nikolauskrismer. I just pushed an update with the properties only in the Feature object. Do you mind having a look if this is ok?
Thanks.

**Comment by nikolauskrismer** [comment]
Took a look ;-)
Everything seems to work now. Even fixed a problem with the geometry (which now is added using the null value by default) for me.

Thanks.
