### ISSUE TITLE
conversion to JTS geometry

### ISSUE THREAD

**Issue by abrin** [opendatalab-de/geojson-jackson#33]
is there a straightforward way to convert between a JTS shape and your GeoJSON shape back and forth?

apologies if I missed it.

**Comment by grundid** [comment]
sorry, I'm not familiar with JTS shape.

**Comment by abrin** [comment]
JTS shapes (Java Topology Suite) https://sourceforge.net/projects/jts-topo-suite/ is the backbone of how SOLR (Lucene), HibernateSpatial, and Geotools represent Spatial objects. So, having a direct transform would facilitate ease of moving between a GeoJSON Point, Polygon, etc. and a more standard java representation of the object.
