### ISSUE TITLE
Publish new versions on Maven central

### ISSUE THREAD

**Issue by SDC2021** [opendatalab-de/geojson-jackson#52]
Hi,

it would be great if we could publish the new versions (1.9 / 1.10) on Maven central...

https://search.maven.org/search?q=g:de.grundid.opendatalab

**Comment by SDC2021** [comment]
@grundid Could you please release the new version? :)

**Comment by grundid** [comment]
Yes, I will release an update ASAP. Maven Repository was very slow yesterday so that the upload timed out.

**Comment by grundid** [comment]
Finally managed to get the update through. It should be available within a few hours.
The version will be 1.12, as other versions have failed.
